root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ."
  delay = 1000
  exclude_dir = ["tmp", "web/ui/node_modules", "data", ".git", "vendor"]
  exclude_regex = ["_test.go"]
  include_ext = ["go", "tpl", "tmpl", "html", "yaml"]
  include_dir = ["api", "config", "internal", "web"]
  kill_delay = "2s"
  send_interrupt = true
  stop_on_error = true

[log]
  time = false

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[misc]
  clean_on_exit = true
